steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/ionic'
    args: ['build']

options:
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: 'gs://www-orcwood-com/'
    paths:
      - 'build/**'